src/PyCall.jl
This avoids warnings about conflicting imports
=> Use a bare module with no imports for ＠pyimport

README.md, REQUIRE
I thought since PackageEvaluator is working nicely with PyCall, it'd be nice to show PyCall is working great on release.
My next PkgEval project is to start testing the various packages that depend on PyCall, which are mostly excluded right now.
I've also thrown in a tweak to the REQUIRE - PyCall is defacto 0.3 only anyway due to Dates, thought it was better to be explicit.
=> Minor tweaks to badges and tracking master instructions

REQUIRE, src/PyCall.jl, src/conversions.jl, src/numpy.jl, src/pybuffer.jl, src/pydates.jl, src/pyinit.jl, src/pytype.jl, test/runtests.jl
=> Fix load error and deprecation warnings on master

src/PyCall.jl, src/pyinit.jl
(additionally removed some code for v0.3 compatibility because that
should be handled by Compat now)
Necessary since JuliaLang/julia#10951
=> Fix name collisions by explicitly qualifying Libdl

src/PyCall.jl, src/pyinit.jl
The first commit is some white space fixes.
The roundtrip test is failing for unknown reason. Haven't looked further yet.
Fix #143.
=> Fix 0.4-dev dlopen breakage

REQUIRE, src/gui.jl
This should address stevengj/PyPlot.jl#136 as well.
I don't know of a clean way of making `Dict{Symbol,Timer}()` compatible with the new timer API, so an if-statement will have to do for now.  `@compat` seems to only work on Timer type declarations, not the type itself.
=> Use v0.4 Timer API

src/PyCall.jl, src/conversions.jl
Ref https://github.com/JuliaLang/julia/pull/11969
I know it's really tempting but unfortunately this is not the correct usage of `NTuple`.
```julia
julia> (Int, 1)::NTuple{Type}
(Int64,1)
julia> (Int, Float64)::NTuple{Type}
(Int64,Float64)
julia> (Int, Float64)::NTuple{TypeVar(:N), Type}
(Int64,Float64)
julia> (Int, 1)::NTuple{TypeVar(:N), Type}
ERROR: TypeError: typeassert: expected NTuple{N,Type{T}}, got Tuple{DataType,Int64}
```
=> Fix incorrect usage of NTuple

deps/build.jl
When running `Pkg.build("PyCall")` on my machine, it seems that `pop!(ENV, "PYTHONHOME")` is called twice, thus failing the second time. This PR simply adds a default argument to the second call.
I'm also having issues with the build script properly finding my `PYTHONHOME` in a virtualenv, so the problem fixed here is probably related to that.
Before
```julia
_
_       _ _(_)_     |  A fresh approach to technical computing
(_)     | (_) (_)    |  Documentation: http://docs.julialang.org
_ _   _| |_  __ _   |  Type "?help" for help.
| | | | | | |/ _` |  |
| | |_| | | | (_| |  |  Version 0.4.0-pre+7393 (2015-09-08 15:09 UTC)
_/ |\__'_|_|_|\__'_|  |  Commit 8161026 (0 days old master)
|__/                   |  x86_64-apple-darwin14.4.0
julia> Pkg.build("PyCall")
INFO: Building PyCall
INFO: …
```
=> Fix error in deps/build.jl due to calling pop!(ENV, "PYTHONHOME") twice.

deps/build.jl
pipe fails silently with a failure to find method call in try/catch
As a result, PYTHONHOME is improperly set and `import site` fails
=> fixed deprecated use of pipe -> pipeline

.travis.yml, REQUIRE, appveyor.yml, deps/build.jl
This is a WIP towards figuring out how Conda can be used as a replacement of system python and it is parallel work to https://github.com/JuliaLang/IJulia.jl/pull/357.
I still haven't figured out the API for how PyPlot/PyCall/IJulia should interact with Conda and if they should require Conda or if the user should add Conda.
=> WIP towards make PyCall use Conda if system python is not found

src/io.jl
=> Remove deprecated FileOffset

README.md, REQUIRE, src/PyCall.jl, src/io.jl, src/pyclass.jl, src/pyinit.jl, src/pytype.jl, test/runtests.jl
Follow-up to #237. Using `type` to create the metaclass was much simpler than using the C API. Everything works, including multiple inheritance and special Python methods (`__init__`, `__len__`, etc.) The interface changed slightly, because we don't use `jlWrap` anymore:
```julia
PyCall.@pydef type PyIO
__init__(self, io::IO; istextio=false) = begin
self[:io] = io
self[:istextio] = istextio
nothing
end
closed.get(self) = !isopen(self[:io])
fileno(self) = fd(self[:io])
....
end
let buf = IOBuffer(false, true), obuf = PyIO(buf)
...
end
```
=> Defining Python classes through `type`

REQUIRE, src/PyCall.jl, src/conversions.jl, src/numpy.jl, src/pyclass.jl, src/pydates.jl, src/pytype.jl, test/runtests.jl
`String`, `Symbol`, `precision(BigFloat)`
Also fix an incorrect use of `unsafe_convert`.
Requires a new tag of `Compat`.
Also includes https://github.com/stevengj/PyCall.jl/pull/260
Requires https://github.com/JuliaLang/Compat.jl/pull/192
=> Fix depwarn on 0.5

src/pytype.jl
```julia
Py_TPFLAGS_HAVE_STACKLESS_EXTENSION = try pyimport("stackless")
Py_TPFLAGS_HAVE_STACKLESS_EXTENSION_; catch 0; end
```
was returning `nothing` instead of returning `0`.  The parser was not as strict about this before I think.
=> Add semicolon between `catch` and return value

src/PyCall.jl, src/conversions.jl, src/gc.jl, src/gui.jl, src/numpy.jl, src/pydates.jl, src/pyinit.jl, src/pytype.jl
This eliminates the `global const` assignments from `__init__`, since this is deprecated and doesn't play well with precompilation (JuliaLang/julia#12010).
=> eliminate "global const foo = bar" from __init__

src/conversions.jl
`Array` as argument type means passing the array by reference, not passing the pointer to a string. This is what's causing https://github.com/JuliaLang/julia/issues/15432 and https://github.com/stevengj/PyCall.jl/issues/254#issuecomment-206515726 (plus incorrect handling in the ABI).
=> Fix incorrect ccall argument type

src/gui.jl, src/io.jl, src/numpy.jl
Would be great to tag another version once this is merged.
This fixes deprecation warnings that show up during precompile.
=> Fix julia 0.5 deprecation warnings

src/pydates.jl, src/pyinit.jl
Fix SegFault with precompilation off.
Noticed this since I was testing packages with precompilation disabled due to https://github.com/JuliaLang/julia/issues/17809
=> Initialize global pointers to NULL explicitly

appveyor.yml
[3.5 is latest supported Python (I assume PyCall/Travis etc. works with it), 3.3 is no longer officially supported.]
You may also want to skip: "In Julia 0.3, sometimes calling a Python function fails"..
to simplify the README.. as no longer supported (and I assume Julia 0.3 itself about to be unsupported (or used), after 0.5 is released).
[ci skip]
=> Test on 3.5

src/PyCall.jl
Python packaged by conda-forge has `conda-forge` in the Python version string. Checking for `conda` as a substring works for both `conda-forge` and `Anaconda`.
=> Python by conda-forge

src/PyCall.jl
In IJulia, I sometimes get deprecation warnings from PyCall. Eg.
```julia
using PyCall
@pyimport math
math.sin
```
(has to be run in three different cells!)
This PR fixes this for Julia 0.5.
=> Fix writemime deprecation warnings

src/numpy.jl, test/runtests.jl
The two errors I left unchanged are
* https://github.com/JuliaPy/PyCall.jl/issues/343
Seems that the solution haven't been finalized yet.
* https://github.com/JuliaLang/julia/issues/19987
Let's see if this can be unbroken in Base. ~~This particular line seems to be really good at catching base parser breakage...~~ (actually it was a different line)
=> Fix a few depwarns and errors on 0.6

src/PyCall.jl, src/conversions.jl, src/pydates.jl, src/pyeval.jl, test/runtests.jl
Test on master might fail with an error similar to
```
signal (4): Illegal instruction
while loading /home/yuyichao/projects/contrib/PyCall.jl/test/runtests.jl, in expression starting on line 318
copy at /usr/share/julia/site/v0.6/PyCall/src/numpy.jl:340
unknown function (ip: 0x7fe154c964f2)
jl_call_method_internal at /build/julia-git/src/julia-avx2/src/julia_internal.h:248
```
and that's https://github.com/JuliaLang/julia/issues/20305
I also decided to work around https://github.com/JuliaLang/julia/issues/19987 since it doesn't seems to have very high priority or trivial to fix (but trivial to workaround)....
=> Fix 0.6 depwarns

src/conversions.jl, test/runtests.jl
Stop mapping all Python objects that support the mapping protocol to
Julia dictionaries.
=> Make dictionary conversion more conservative

src/PyCall.jl, src/serialize.jl, test/runtests.jl
This is my first crack at doing this. This allows passing PyObjects around in RemoteChannels. 
One issue with this:
This works:
```julia
using PyCall
@everywhere using PyCall
```
But this segfaults:
```julia
@everywhere using PyCall
```
I know the latter does the NxN loading thing and isn't advized, but it's something people will do. Advice is welcome!
=> Custom serialization for PyObject

src/startup.jl
We've since re-arranged the way we load dynamic libraries a bit, making
the current detection code ineffective. This should address most instances
of pyjulia accidentally loading the wrong python version.
=> Fix in-process symbol resolution

src/callback.jl
Fixes https://github.com/JuliaPy/pyjulia/issues/105
I thought it would also fix #343, but the example in that issue description seems to work fine for me on 0.6 release without this PR (but the issue is still open).
Directly calls `Core._apply_latest` with a closure over kw args as in https://github.com/JuliaLang/julia/pull/22646 for 0.6.
cc @TsurHerman
=> RFC: Use invokelatest in jl_Function_call

src/startup.jl
It turns out that, for some python versions on OS X, `main` is not a public symbol. However, all OS X executables have the `_mh_execute_header` Symbol, so try to use that instead on OS X.
=> Try to fix in-process symbol resolution on OS X

src/PyCall.jl, src/callback.jl, src/pyinit.jl, src/pytype.jl, test/runtests.jl
All objects are callable nowadays, restricting to `Function` is odd and
precludes things like constructing types from Python in pyjulia.
=> Allow calling things that are not Functions

src/conversions.jl, test/runtests.jl
Makes the following work in pyjulia:
```python
import julia
j = julia.Julia()
j.eval("""
module FooBar
export Foo, bar
type Foo
i::Int
end
function bar(a::Array{Foo,1})
return sum([f.i for f in a])
end
end # module
""")
j.using("FooBar")
foo1 = j.Foo(1)
foo2 = j.Foo(2)
j.bar([foo1, foo2])
```
before this would fail because the julia-side type was `Vector{Any}`.
=> Tighten return type for conversion to `Array`

src/conversions.jl, test/runtests.jl
Before this PR, `Int128`s could not be converted to `PyObject`s:
```julia
using PyCall
julia> i=12345678901234567890; @show typeof(i); PyObject(i)
typeof(i) = Int128
ERROR: InexactError()
Stacktrace:
[1] macro expansion at ...(.julia/v0.6/PyCall/src/exception.jl:78 [inlined]
[2] PyCall.PyObject(::Int128) at .../.julia/v0.6/PyCall/src/conversions.jl:10
```
=> fixed missing conversion of Int128

README.md, REQUIRE, deps/build.jl, deps/depsutils.jl, src/PyCall.jl, src/callback.jl, src/conversions.jl, src/exception.jl, src/gc.jl, src/io.jl, src/numpy.jl, src/pybuffer.jl, src/pydates.jl, src/pyinit.jl, src/pyiterator.jl, src/pytype.jl, src/serialize.jl, src/startup.jl, test/runtests.jl
Update to work with Julia 0.7.
=> WIP: 0.7 compatibility

README.md, src/io.jl, src/pyclass.jl, test/runtests.jl
I used [`MacroTools.splitdef`](https://github.com/MikeInnes/MacroTools.jl#function-definitions) to clean up the method definition code. This enables support for long-form function definitions (along with parametric types and return types, which might not get much use). I also now create types with a method dictionary. It will help #470.
(Sorry for the other PR; I had forgotten to branch)
=> @pydef improvements

src/conversions.jl
* Avoid using exceptions for control flow when a PyObject doesn't have the `"__array_interface__"` attribute. Provides 5-6x speed up for PyAny conversions for heterogenous lists: `@benchmark convert(PyAny, PyObject([1,2,"c"]))`
* **Was that the only exception that try block was supposed to catch?**
* Avoid double check for isdict in PyDict constructor
* Couple of other minor changes
=> Misc fixes

README.md, deps/build.jl
Now that Conda defaults to Python 3 (JuliaPy/Conda.jl#108), to be consistent PyCall should default to `python3` on non-Mac Unices.
Python 2 is still supported, you just need to configure PyCall with `ENV["PYTHON"]="python2"` or similar.  Existing installations will not be affected because PyCall remembers what Python you last configured with.
See also #435.
=> default to python3 on Unix

src/conversions.jl, src/startup.jl, test/runtests.jl
Fixes #510: make sure integer conversions call the `__int__` method in Python 3.   Also use `long long` conversions with overflow checking in Python 3, and fix automatic `BigInt` conversion in Python 3.2 or later.
Better fix for #481: we don't need to call the `.item` field of NumPy scalar types in Python 3 as long as we use a conversion that calls the `__int__`, `__float__`, or `__complex__` methods.
=> better handling of scalar conversions, particularly in Python 3

.travis.yml, appveyor.yml, src/conversions.jl, src/pyiterator.jl
I've spent the past week hoping that someone better versed in the new iteration protocol than me might take a crack at this, but at least the tests pass.
The remaining deprecation warnings  in `pkg> test PyCall` (see below) are mostly related to implicit conversion/construction of `Number` types; it's not quite the same issue but I'll wait for the resolution of https://github.com/JuliaDiff/ForwardDiff.jl/pull/342 before defining
```julia
(::Type{T})(x::PyObject) where {T<:Number} = convert(T, x)
```
or at the very least,
```julia
(::Type{T})(x::PyObject) where {T<:Integer} = convert(T, x)
```
---
```julia
┌ Info: Python version 3.6.5 from libpython3.6m, PYTHONHOME=/usr:/usr
│ ENV[PYTHONPATH]=/opt/ros/melodic/lib/python2.7/dist-packages:/home/schmrlng/catkin_ws/devel/lib/python2.7/dist-pack …
```
=> Update to 0.7- iteration protocol (start/next/done -> iterate)

appveyor.yml
solves https://github.com/JuliaPy/PyCall.jl/pull/543#issuecomment-416404216
Closes #520
=> Use correct Python version in x64 AppVeyor

appveyor.yml, src/pydates.jl
Running tests with Python 3.7 segfaults. I try to reproduce the issue on Travis in this PR.
The minimal code I found to cause the segfault was:
```julia
using PyCall, Dates; convert(PyObject, DateTime(2013))
```
Added: closes #544
=> Segfault with Python 3.7

src/PyCall.jl, src/callback.jl, src/pyiterator.jl, src/pytype.jl, test/runtests.jl
closes #551
I'm not very familiar with Python C API but I think this fixes the bug.
=> Don't steal reference from existing Python object

src/pyfncall.jl
Since `PyObject_Call` returns a new reference, we don't need to increment the reference count.
https://docs.python.org/3/c-api/object.html#c.PyObject_Call
closes #542
=> Fix memory leak

src/pyclass.jl
`@pydef` declares the class `const` which if done in the local scope is deprecated in 0.7 / errors on 1.0. I just removed the `const`. I suppose it could still remain there in the global scope, which would offer slightly better type-stability / performance, but if you're building / calling into a Python class I would argue the overhead is likely to be insignificant in most cases.
=> remove const declaration in `@pydef` which is deprecated in local scope

src/PyCall.jl
=> Do not run `conda install` automagically (unless Conda.jl is used)

deps/build.jl, deps/find_libpython.py
as I suggested in https://github.com/JuliaPy/pyjulia/pull/190#issuecomment-418196179
<strike>
I think we can also remove this part (untouched ATM):
https://github.com/JuliaPy/PyCall.jl/blob/49029e0347a550ca15df06558fe5aad9ca80479a/deps/build.jl#L95-L134
`ctypes.util.find_library` used in `find_libpython.py` is probably good enough.  What do you think?
</strike>
(Edit: the fallback should stay: https://travis-ci.org/JuliaPy/PyCall.jl/builds/425108395)
=> Use find_libpython.py in deps/build.jl

src/gui.jl
Maybe fix https://github.com/JuliaPy/PyPlot.jl/issues/316
=> Support closing the first (root) window in Tk

deps/build.jl
In case the testing "infrastructure" I introduced in #595 was too much, this is a quick fix version.
closes #595
=> Fix show_dlopen_error

README.md, src/pyclass.jl, test/runtests.jl
Before this commit, `@pydef` and `@pydef_object` did not support the creation of
python classes with [class variables][1]. I have expanded `@pydef` to support
class variables with the following syntax:
```julia
@pydef mutable struct ObjectCounter
obj_count = 0 # Class variable
function __init__(::PyObject)
ObjectCounter[:obj_count] += 1
end
end
```
closes #513
[1]: https://docs.python.org/3/tutorial/classes.html#class-and-instance-variables
=> Allow @pydef to define classes with class variables

src/pyinit.jl, src/pytype.jl, test/runtests.jl
I have added [weak reference support][1] for `pyjlwrap` types, following the
documentation for Python 3+. Adding weak reference support for Python 2.x seems
much the same as in 3.x, however 3.x does not use Py_TPFLAGS_HAVE_WEAKREFS,
which also does not seem necessary for 2.x. Simple testing suggests that this is
working as expected.
Closes JuliaPy/PyPlot.jl#21
Closes #158
[1]: https://docs.python.org/3/extending/newtypes.html#weak-reference-support
=> Add weakref support for pyjlwrap types

src/PyCall.jl, src/pyinit.jl, test/runtests.jl
closes https://github.com/JuliaPy/pyjulia/issues/208
It's a bit scary to play with the shutdown process of two GCs. But it seems to work in simple tests...
=> Finalize Python runtime while shutting down Julia

src/pyiterator.jl, test/runtests.jl
This is what I proposed in https://github.com/JuliaPy/PyCall.jl/issues/593
=> add pyiterate

src/callback.jl, src/exception.jl, src/io.jl, src/pyiterator.jl, src/pytype.jl
I have added a back-trace to the description of exceptions coming from Julia
that are subsequently wrapped in Python exceptions.
This makes it much easier to find the source of errors in Julia code being
called from Python functions.
Closes #607
=> Make Julia exceptions wrapped in Python Exceptions more informative

benchmarks/arrayperf.jl, src/PyCall.jl, src/conversions.jl, src/numpy.jl, src/pyarray.jl, src/pybuffer.jl, test/runtests.jl, test/testpybuffer.jl
This is the last one for now 😄
Speedups for PyArray conversion using Python's Buffer interface. `PyArrayFromBuffer` could become the default constructor for PyArray, if this looks good.
* ~15x speedup for `PyArray(o::PyObject)`
* `PyArrayFromBuffer(o::PyObject)` further 4x faster PyArray creation (~60x faster than master)
* `setdata!` for fast reassignment of data ptr in PyArray when you know the array is the right shape (~500x faster than creating a new PyArray on master - not an apples to apples comparison, but still good to have)
* Workhorse is `PyArrayInfoFromBuffer(o::PyObject)` - a faster way to get PyArray_Info from numpy than extracting values from the `__array_interface__`
* (speculative) ArrayFromBuffer no copy conversion to Julia Array
* PyArray_Info parameterised T,N and …
=> PyArray conversion speedups and PyArrayFromBuffer

src/pybuffer.jl
Incorporates change introduced in #603
=> Fix Segfault during finalization

src/pybuffer.jl, test/testpybuffer.jl
Ahh oops. So, apparently you're supposed to use native sizes by default when parsing the buffer protocol format strings. I did the opposite in #487.
Current master
```
using PyCall
py"""
import numpy as np
"""
nparr = py"np.array([1,1,1,1])"o
nparr["dtype"]  # PyObject dtype('int64')
convert(PyAny, nparr)
```
returns `Int32[1,0,1,0]` \*
It should just be `Int[1,1,1,1]`
This actually caused me a bug in some relatively large distributed code, that I found very hard to track down. So karmically, pretty interesting.
At least it didn't make it to a release.
\* The [1, 0, 1, 0] is also in part due to a bug in f_contiguous for 1d arrays when `stride != sizeof(T)` - I will post a PR with a fix for that next week, I need to make some other changes to get the tests right for that. This is the minor …
=> Use native sizes by default when parsing buffer format string

src/pyarray.jl, src/pybuffer.jl, test/testpybuffer.jl
Changes by commit
1. [Add support for non-contiguous PyArrays](https://github.com/JuliaPy/PyCall.jl/commit/cccd18874984642d5bcbddaf4c625a71b420b4d7): Restore support for non-contiguous PyArrays (I think they used to work before #487?)
2. [Fix f_contiguous for 1d arrays](https://github.com/JuliaPy/PyCall.jl/pull/623/commits/ac2ea1e22adc5c4b94dfefb3839512ecdf8e91b2): without this non-contiguous 1d PyArrays could have the f_contig flag set incorrectly to true. This would cause an incorrect conversion to julia for such arrays with a `convert(PyAny, non_contig_1d_array)` (see the [1,0,1,0] example in #621/the "1d non-contiguous" testset in this PR)
3. [Simplify Copy(::PyArray)](https://github.com/JuliaPy/PyCall.jl/pull/623/commits/8e5be56b6cd15cc4308176da44e33de3107ba403): With f_contiguous …
=> Restore support for non-contiguous PyArrays, fix f_contiguous, simplify copy(::PyArray)

README.md, benchmarks/pywrapfn.jl, src/PyCall.jl, src/callback.jl, src/conversions.jl, src/exception.jl, src/gui.jl, src/io.jl, src/numpy.jl, src/pyclass.jl, src/pydates.jl, src/pyfncall.jl, src/pyinit.jl, src/pyoperators.jl, src/pytype.jl, src/serialize.jl, test/runtests.jl, test/testpybuffer.jl
The intent of this PR is to use 0.7/1.0's getproperty functionality to make `o.foo` behave as in Python, i.e. to map it to the current `o[:foo]`.
=> WIP: override get/setproperty and propertynames

src/PyCall.jl, src/pydates.jl, src/pyoperators.jl, src/pytype.jl, src/serialize.jl, test/runtests.jl
Whenever we convert a `PyObject` to a `PyPtr`, we need to be a bit paranoid about the possibility that the `PyObject` will be garbage-collected (which will decref the underlying Python object) before we are done with the `PyPtr`.
=> be more careful about potential gc of pyptrs

src/PyCall.jl, test/runtests.jl, test/testpybuffer.jl
Now that `o.foo` mirrors Python, we also want `o[foo]` to mirror Python.  Unfortunately, PyCall currently makes `o[integer]` in Julia act like `o[integer-1]` in Python, to emulate 1-based access.   This PR deprecates 1-based indexing of `PyObject` so that in PyCall 2.0 we can switch to 0-based indexing.
=> deprecate o[integer] so that we can transition to 0-based access

src/PyCall.jl
=> avoid stealing refs in pyreturn

src/PyCall.jl, test/runtests.jl
Before:
```julia
julia> os = pyimport("os")
PyObject <module 'os' from '/home/takafumi/.virtualenvs/julia/lib/python3.7/os.py'>
help?> os.path.join
ERROR: MethodError: no method matching Base.Docs.Binding(::PyObject, ::Symbol)
...
```
After:
```julia
help?> os.path.join
Join two or more pathname components, inserting '/' as needed.
If any component is an absolute path, all previous path components
will be discarded.  An empty last part will result in a path that
ends with a separator.
```
=> Make ?obj.property work for obj::PyObject

src/pyinit.jl
Before this PR, using Python GUI and invoking some I/O in `atexit` resulted in a segfault:
```julia
$ julia --startup-file=no --banner=no
julia> atexit() do
run(`echo hello`)
end
julia> import PyPlot
PyPlot.plot([1], [2], "o")
1-element Array{PyCall.PyObject,1}:
PyObject <matplotlib.lines.Line2D object at 0x7fbd5b93bda0>
julia>
signal (11): Segmentation fault
in expression starting at REPL[2]:0
hello
PyUnicode_InternInPlace at /usr/lib/libpython3.7m.so.1.0 (unknown line)
_PyUnicode_FromId at /usr/lib/libpython3.7m.so.1.0 (unknown line)
_PyType_LookupId at /usr/lib/libpython3.7m.so.1.0 (unknown line)
unknown function (ip: 0x7fbd7df7e773)
PyObject_GetAttrString at /usr/lib/libpython3.7m.so.1.0 (unknown line)
getproperty at /home/takafumi/.julia/dev/PyCall/src/PyCall.jl:295
#7 at …
```
=> Stop all GUI event loops before Py_Finalize

.travis.yml, README.md, deps/build.jl, deps/depsutils.jl, src/PyCall.jl, src/pyinit.jl, src/startup.jl, test/runtests.jl, test/test_venv.jl
This PR grew out of a small feature addition to a patch that includes a few more. Here is a new summary:
* Main feature addition: Control Python environment at run-time by the environment variables `PYCALL_JL_RUNTIME_PYTHON` (and `PYCALL_JL_RUNTIME_PYTHONHOME`).
* fix #410: Support building Pycall against a Python executable generated by `python -m venv`.
* Refactoring: I merged how `Py_SetPythonHome` and `Py_SetProgramName` are `ccall`ed with and without `PYCALL_JL_RUNTIME_PYTHON`.  `wpyprogramname` and `wPYTHONHOME` are removed.
---
Original summary:
I suggest to let users control Python environment at runtime by (say) `ENV["PYCALL_JL_RUNTIME_PYTHON"]` (and `ENV["PYCALL_JL_RUNTIME_PYTHONHOME"]`).  This can be used to make sure that Julia and Python environments for a project are fully …
=> Support virtual environment

src/conversions.jl, src/numpy.jl, src/pybuffer.jl, test/runtests.jl
Fixes `array2py` to use `CartesianIndex` rather than linear indexing.  Also adds special-case conversions for `Transpose` and `Adjoint` arrays.
Closes JuliaPy/PyPlot.jl#380, JuliaPy/PyPlot.jl#400, JuliaPy/PyPlot.jl#391, JuliaPy/PyPlot.jl#362.
Also has a bugfix for a typo in our `array_format(::PyBuffer)` function for complex arrays.
=> fix array2py and friends for adjoints etc.

src/startup.jl
I added support for `--compiled_modules=no` in PyJulia https://github.com/JuliaPy/pyjulia/pull/236 (which can be used for yet another workaround for the precompilation issue).  But, it requires a small fix in PyCall.jl.
=> Make PyJulia work with --compiled-modules=no

src/startup.jl
Without this change, PyJulia (`symbols_present == true`) path of startup.jl in Windows yields
```
LoadError: LoadError: MethodError: no method matching findfirst(::Array{UInt16,1}, ::Int64)
Closest candidates are:
findfirst(::Union{AbstractString, AbstractArray}) at array.jl:1661
findfirst(!Matched::Function, ::Any) at array.jl:1735
findfirst(::Any) at array.jl:1652
in expression starting at C:\Users\appveyor\.julia\packages\PyCall\RQjD7\src\startup.jl:41
in expression starting at C:\Users\appveyor\.julia\packages\PyCall\RQjD7\src\PyCall.jl:37
```
(see https://ci.appveyor.com/project/Keno/pyjulia/builds/22976283/job/gqgiddula060yi1e#L417 which is the result of https://github.com/tkf/pyjulia/commit/7618f648d628403b98d606e9c2d1a00cae3159e3 in https://github.com/JuliaPy/pyjulia/pull/236) …
=> Fix findfirst usage for Julia 1.0

README.md
I was struggling with  PyCall as it wasn't picking up my python installation since I thought the `PYTHON` env variable should point to the python **directory** as opposed the  python executable.
=> Clarify readme on python exe path

src/conversions.jl, src/pyarray.jl, src/pybuffer.jl, src/pytype.jl, test/runtests.jl, test/testpybuffer.jl
Add bounds-checking, GC rooting, and `CartesianIndex` support in `PyArray`. Fixes conversion for arrays of pointers/pyptrs and 0-dimensional arrays.
Fixes JuliaPy/PyPlot.jl#431
=> various fixes to array conversions

src/pytype.jl
A cleaner solution to JuliaLang/julia#31473 and #670.
=> avoid jl_value_ptr

.gitignore, .travis.yml, aot/README.md, aot/compile.jl, aot/julia.sh, aot/precompile.jl, aot/runtests.sh, src/pyinit.jl
This PR makes PyCall.jl compatible with PackageCompiler.jl and add some tests.
Quick usage:
```console
$ aot/compile.jl --color=yes
...
$ aot/julia.sh --compiled-modules=no --startup-file=no --banner=no
julia> @time using PyCall
0.001537 seconds (309 allocations: 16.688 KiB)
```
Slightly more detailed docs in: [aot/README.md](https://github.com/tkf/PyCall.jl/blob/aot/aot/README.md)
=> Make PyCall.jl AOT-compilable

aot/compile.jl
This PR fixes the following `LoadError`.
Running `compile.jl` we obtain the following error:
```bash
$ julia -e 'import Pkg; Pkg.pkg"add PyCall#master"'
$ cd ~/.julia/packages/PyCall/guUh9/
$ aot/compile.jl
Updating registry at `~/.julia/registries/General`
Updating git-repo `https://github.com/JuliaRegistries/General.git`
Resolving package versions...
Updating `~/.julia/packages/PyCall/guUh9/aot/Project.toml`
[1914dd2f] + MacroTools v0.4.5
Updating `~/.julia/packages/PyCall/guUh9/aot/Manifest.toml`
[34da2185] + Compat v2.1.0
[1914dd2f] + MacroTools v0.4.5
[2a0f44e3] + Base64
[ade2ca70] + Dates
[8bb1440f] + DelimitedFiles
[8ba89e20] + Distributed
[b77e0a4c] + InteractiveUtils
[76f85450] + LibGit2
[8f399da3] + Libdl
[37e2e46d] + LinearAlgebra
[56ddb016] + Logging
[d6f4376e] + Markdown …
```
=> fix aot script

src/exception.jl
fix https://github.com/JuliaPy/pyjulia/pull/262#issuecomment-479778182
=> Fix pyraise

.gitignore, Project.toml
We'll need a `Project.toml` for the next release https://discourse.julialang.org/t/22677
=> Add Project.toml

Project.toml
Can we release 1.91.2 before removing REQUIRE #677?
=> Bump to 1.91.2

src/PyCall.jl, src/exception.jl, src/pyeval.jl, src/pyfncall.jl, src/pyiterator.jl
=> Use disable_sigint instead of sigatomic_(begin|end)

aot/precompile.jl, src/pyinit.jl
In PR #651, I introduced code to empty `npy_api` in `__init__` but forgot to reset `npy_initialized`.  This introduces a bug if `npyinitialize` is called during sysimage compilation (`--output-o` mode) because the main body of `npyinitialize` is not run at run-time.
I checked that [undoing the fix](https://github.com/tkf/PyCall.jl/commit/25ff0ad3b9c1b44c55b20072c543ec1b385dafc7) breaks [the AOT compilation test](https://travis-ci.com/tkf/PyCall.jl/jobs/201289387).
=> Support calling PyCall.npyinitialize() during sysimage compilation

README.md
The comparison with julia was removed in https://github.com/JuliaPy/PyCall.jl/commit/7f37853119aae9a7fff6c80c97f5c5c6f56e1896
=> remove outdated note in the README

src/PyCall.jl, test/runtests.jl
it seems to get seg-faulted so easily on the `PyNULL` object.
this PR checks `ispynull(o)` in `propertynames(o::PyObject)`.
```
julia> using PyCall: PyNULL
julia> o = PyNULL()
PyObject NULL
julia> o.<TAB>
signal (11): Segmentation fault: 11
in expression starting at no file:0
_PyEval_EvalCodeWithName at /Library/Frameworks/Python.framework/Versions/3.7/Python (unknown line)
_PyFunction_FastCallDict at /Library/Frameworks/Python.framework/Versions/3.7/Python (unknown line)
macro expansion at /Users/wookyoung/.julia/dev/PyCall/src/exception.jl:93 [inlined]
#110 at /Users/wookyoung/.julia/dev/PyCall/src/pyfncall.jl:43 [inlined]
disable_sigint at ./c.jl:446 [inlined]
__pycall! at /Users/wookyoung/.julia/dev/PyCall/src/pyfncall.jl:42 [inlined]
_pycall! at …
```
=> propertynames for PyNULL

src/gc.jl
```jl
julia> function f()
true && ArgumentError("hi")
1
end
f (generic function with 1 method)
julia> f()
1
```
=> Throw an error instead of just creating one

REQUIRE
=> Remove REQUIRE

deps/find_libpython.py
Use `sysconfig.get_system_var("VERSION")` as last resort as there is a possibility that it is not updated.
```python
>>> sys.version_info
sys.version_info(major=3, minor=8, micro=0, releaselevel='final', serial=0)
>>> sysconfig.get_config_var("VERSION")
'3.7'
>>> sysconfig.get_python_version()
'3.8'
```
Closes #752
=> Improving find libpython

src/PyCall.jl
Similar to JuliaPlots/Plots.jl#2544 … this is a new feature of Julia 1.4.
=> set optimization level to 1 for faster load time

src/PyCall.jl, src/exception.jl
This PR tries to address the printing of stack traces in Julia callbacks and fix #770, while also leaving the door open for further improvements.
The problem I wanted to solve is the fact that errors and stack traces thrown by a Julia callback executed by python, such as 
```python
julia> py"$error('I am ugly')"
```
loses formatting when being displayed. 
This is because currently we _render_ the exception to a string when it is thrown, return it to python as a python error, which then is returned to Julia again, and displays it.
This is especially painful in wrapper packages such as Tensorflow.jl, Jax.jl or several others.
In the process formatting is lost. 
My solution:
When a Julia callback throws, don't render the callback immediately. Instead return a custom Error type, `PyJlError`, …
=> [RFC] Throw a special exceptions in Julia callbacks (Fix #770)

src/PyCall.jl, test/runtests.jl
Until issue #645 is resolved, this is a  measure to not mislead the user.
=> Emit more accurate error message

src/pyinit.jl
In some environments, `__main__` isn't a module, eg on an [ipyparallel](https://ipyparallel.readthedocs.io/en/latest/) worker `__main__` is a `IPython.core.interactiveshell.DummyMod`, causing PyCall to error on loading because that `pyeval_` is trying to use `__main__` by default. Or worse, if you've compiled a custom sysimage with PyCall (eg for pyjulia), then an error during `__init__` means a segfault. This fixes that. 
Actually, with this PR, I can now run an `ipyparallel` cluster of Python workers calling Julia via pyjulia w/ custom sysimage 🎉
```
$ ipcluster start -n 1 & # start workers
$ ipython
In [1]: import ipyparallel as ipp 
...: c = ipp.Client() 
...: c.ids …
```
=> fix `PyCall.__init__` when no `__main__` present

src/conversions.jl
Trivial fix to give the user-specified `pytype_mapping`s precedence over the default built-ins, such that things which subclass Python `array`, `dict`, etc... can have custom mappings in PyCall. 
@stevengj mentions in https://github.com/JuliaPy/PyCall.jl/issues/700#issuecomment-516049934 that you're trying to move away from needing these conversions at all, but given that its a year later and we're still not quite there, I think this is still useful in the meantime. 
Closes https://github.com/JuliaPy/PyCall.jl/issues/751, https://github.com/JuliaPy/PyCall.jl/issues/700
=> give pytype_mapping precendence over default mappings

.github/workflows/aot.yml, .github/workflows/conda.yml, .github/workflows/system.yml, test/check_deps_version.jl, test/test_build.jl
I've been using GitHub Actions in PyJulia for a while and it's been working nicely. The best part of it is that we don't need OS-specific configurations and also Python on macOS just works. It's also nice that we don't need to click through pages to find out the failing combination.
Since travis-ci.org will be closed down on December 31, 2020, maybe it's a good opportunity to move to GitHub Actions? (Although migration to travis-ci.com is another option.)
https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom?e=%5BUNIQID%5D
https://docs.travis-ci.com/user/migrate/open-source-repository-migration
Some notes:
* I separated out conda and AOT tests from the system Python tests. Although we can save ~20 lines if we combine system and conda Python tests, I think it's cleaner to …
=> Use GitHub Actions to run CI

README.md
Closes #824 
Closes #828 
This PR adds the following badges to the README:
1. GitHub Actions CI
2. PkgEval
3. Codecov
And deletes the following badges from the README:
1. Travis CI
2. Appveyor CI
3. Coveralls
cc: @tkf 
cc: @stevengj
=> README: add GH Actions, PkgEval, and CodeCov badges; delete Travis, AppVeyor, and Coveralls badges

test/runtests.jl
close #812
It would be nice to make these tests more robust. But, for now, I think just skipping them in PkgEval is a good option.
=> Skip test_venv.jl and test_build.jl in PkgEval

src/PyCall.jl, test/runtests.jl
fix #816
An MWE
```julia
py"""
class Issue816(object):
def _repr_html_(self):
return "<h1>Issue816</h1>"
"""
showable("text/html", py"Issue816()")  # => true
showable("text/html", py"Issue816")  # => throws
```
```
ERROR: PyError ($(Expr(:escape, :(ccall(#= /home/takafumi/.julia/dev/PyCall/src/pyfncall.jl:43 =# @pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, pyargsptr, kw))))) <class 'TypeError'>
TypeError("_repr_html_() missing 1 required positional argument: 'self'")
Stacktrace:
[1] pyerr_check at /home/takafumi/.julia/dev/PyCall/src/exception.jl:62 [inlined]
[2] pyerr_check at /home/takafumi/.julia/dev/PyCall/src/exception.jl:66 [inlined]
[3] _handle_error(::String) at /home/takafumi/.julia/dev/PyCall/src/exception.jl:83
[4] macro expansion at …
```
=> Don't try to call `_repr_*_` on a class

.github/workflows/aot.yml
I'm not sure why #831 did not catch this but AOT test fails because of missing Numpy
https://github.com/JuliaPy/PyCall.jl/runs/1167697076#step:10:44
This PR fixes it.
=> Install Numpy on AOT test

Project.toml
close #822
Commits since the last release: https://github.com/JuliaPy/PyCall.jl/compare/v1.91.4...tkf:release-v1.92.0
=> Release v1.92.0

Project.toml, src/PyCall.jl
I should've used `pyversion` instead of `pyversion_build` so that it works in PyJulia mode.
close https://github.com/JuliaPy/pyjulia/issues/424
@stevengj Can we release 1.92.1 just after merging this PR?  I incremented the version in Project.toml.
=> Fix get_real_method; don't use pyversion_build

.github/workflows/aot.yml, aot/runtests.sh, src/conversions.jl
I extracted this commit from the "transpose_and_slice" branch to focus on fixing the tests and AOT now that several issues have been resolved.
=> Fix tests, Core.TypeofVararg for Julia 1.7 and AOT

src/numpy.jl
Patch as suggested by Carsten Bauer in #922.
---
As discussed in #922, the new BLAS trampoline magic might allow us to avoid this issue altogether, but this is nontrivial, as it would involve loading MKL in two different configurations even if it did work (the libtrampoline author wasn't sure about that either). For now, this avoids the annoying warning every time PyCall is loaded.
=> Avoid deprecated BLAS.vendor() in MKL conflict check

src/pyinit.jl
=> flush Python I/O in IJulia

src/pyfncall.jl, test/runtests.jl
if `args` on L101 is empty, then `args[1]` in `isexpr()` would throw `BoundsError: attempt to access 0-element Vector{Any} at index [1]`
```julia
julia> ex = :(f()::Float64)
:(f()::Float64)
julia> args = ex.args[1].args[2:end]
Any[]
julia> args[1]
ERROR: BoundsError: attempt to access 0-element Vector{Any} at index [1]
Stacktrace:
[1] getindex(A::Vector{Any}, i1::Int64)
@ Base ./array.jl:924
[2] top-level scope
@ REPL[118]:1
```
=> fix BoundsError of args[1] when args is empty

Project.toml, deps/build.jl
Right now PyCall.jl automatically installs numpy into a conda environment. This install cannot be disabled. If this occurs from within an existing conda environment, it can overwrite the numpy installed by a conda-forge build. This violates the assumptions of conda-forge, and can silently corrupt any conda env that depends on numpy.
This issue was noticed in https://github.com/conda-forge/pysr-feedstock/pull/85, manifesting in this issue: https://github.com/conda-forge/scipy-feedstock/issues/238. We believe this is caused by the line:
https://github.com/JuliaPy/PyCall.jl/blob/bcaba00d1e2c412b2f61d33343ef5a9ab1b9258a/deps/build.jl#L79
This PR enables the `PYCALL_INSTALL_NUMPY` environment flag which can be set to `false` to disable the `Conda.add("numpy")` line and prevent the corruption …
=> Urgent: add option to disable numpy install / prevent corruption of conda-forge environments

Project.toml, src/PyCall.jl, test/runtests.jl
This updates deprecated code introduced in https://github.com/JuliaPy/PyCall.jl/pull/1039. We found this since our tests using some operations from PyCall.jl with `@test_nowarn` failed.
=> fix depwarn

Project.toml
Fixes #1064 
Almost all stdlibs should just use a compat entry of `"< 0.0.0, 1"`. So e.g.
```toml
StdlibName = "< 0.0.1, 1"
```
The `SHA` stdlib is an exception, because it should be:
```toml
SHA = "< 0.0.1, 0.7, 1"
```
=> Fix the stdlib compat entries
