src/pyinit.jl

Fix for JuliaLang/julia#10328

---

src/conversions.jl

Fix 0.3 deprecated types

---

src/PyCall.jl
src/conversions.jl
src/numpy.jl
src/pybuffer.jl
src/pyinit.jl
test/runtests.jl

There are more dlopen issues though... Will comment on the dlhandle PR.

Fix deprecated ntuple signature

---

src/PyCall.jl

With JuliaLang/julia#9609 we can avoid the hack from #110

Create baremodule directly with sufficiently new Julia

---

src/PyCall.jl

This makes it possible to call ``pyeval`` with class definitions and then later refer to those class definitions in a subsequent call to ``pyeval``.

Added ability to reuse local dictionary across calls to pyeval

---

README.md
REQUIRE
src/conversions.jl
src/exception.jl
src/pydates.jl

Requires https://github.com/JuliaLang/Compat.jl/pull/141

Fix deprecation warnings on 0.4

---

src/PyCall.jl
src/conversions.jl
src/gui.jl
src/io.jl
src/numpy.jl

This adds some basic documentation for some of the exported APIs.

Add docs for some exported functions

---

README.md
src/PyCall.jl
src/numpy.jl
test/runtests.jl

Updated version of PR #85 by Kevin Squire.

PyReverseDims(::StridedArray) constructor

---

src/PyCall.jl
src/pyinit.jl
test/runtests.jl

For a detailed explanation of the problems, see https://github.com/zeromq/pyzmq/issues/861.
Fixes #87.

Work around Windows Activation Context problems

---

.travis.yml
README.md

0.3 support was dropped.

---

src/numpy.jl
test/runtests.jl

Support Float16 arrays as arrays with dtype=np.float16

add suppport for Float16

---

REQUIRE
src/conversions.jl
src/exception.jl
src/gui.jl
src/startup.jl
test/runtests.jl

Fix 0.6 depwarn in tests and fix broken macros

---

src/conversions.jl

eltype wasn't defined for ::Type{PyDict{K,V}}

Fixed eltype bug.

---

src/PyCall.jl
test/runtests.jl

Expose docs to Julia

---

REQUIRE
src/conversions.jl

~~**DO NOT MERGE NOW!!!!**~~
~~This requires https://github.com/JuliaLang/Compat.jl/pull/325 and a new tag. I'm using this (and other) PR's to check if the implementation is correct.~~
Ready now.

Fix 0.6 abstract type declaration depwarn

---

README.md
src/PyCall.jl
test/runtests.jl

I needed to use a with statement with a ContextManager, so I went ahead an implemented the suggestion from https://github.com/JuliaPy/PyCall.jl/issues/154#issuecomment-117811984. Let me know if this is something you'd like to have, I'm also happy to make any further changes.

add @with macro

---

src/pytype.jl

update to using tuple type for cfunction

---

src/pytype.jl

I thought this was ok, because the error would get propagated, but pyjulia
doesn't have a toplevel error handler for various things, causing problems here.
Instead, try to fall back to the generic python method for missing fields.
Fixes https://github.com/JuliaPy/pyjulia/issues/116

Don't attempt to get a non-existent field

---

test/runtests.jl

Accidentally left out of my last PR.

Test that the correct error is thrown in getattr fallback

---

src/gc.jl

I was just in the neighborhood.

Fix typo in error message

---

test/runtests.jl

First of a few PRs coming up - add `?w=1` or `&w=1` to the url to see this without whitespace changes.
```
Test Summary: | Pass  Total
PyCall        |  424    424
```

Wrap tests in a testset

---

README.md

jverzani's is currently 1 commit behind.
[skip ci]

Better link?

---

.travis.yml
src/conversions.jl

bugfix in numpy scalars

---

.travis.yml
appveyor.yml
src/PyCall.jl
src/conversions.jl
src/startup.jl
test/runtests.jl

final deprecation fix for 1., maybe!

Fix "all" of 1.0 issues.

---

src/pyfncall.jl
test/runtests.jl

fix non-reentrancy and lack of gc in recent pycall optimization

---

.travis.yml

based on https://github.com/pytest-dev/pytest/blob/799b72cf6f35c4c4c73797303d3f78c12a795f77/.travis.yml#L38-L52

Test also with Python 3 in macOS

---

.travis.yml
README.md
REQUIRE
appveyor.yml
deps/build.jl
deps/depsutils.jl
src/PyCall.jl
src/conversions.jl
src/gui.jl
src/io.jl
src/pyarray.jl
src/pybuffer.jl
src/pydates.jl
src/pyinit.jl
src/pyiterator.jl
src/pyoperators.jl
src/serialize.jl
src/startup.jl
test/runtests.jl
test/test_pyfncall.jl
test/testpybuffer.jl

drop 0.6 support

---

src/numpy.jl

warn if Julia & numpy are linked with MKL

---

README.md
src/pyeval.jl
test/runtests.jl

fixes #599 (the other part of #599 is already tracked by #348)

Use separate Python namespace in py"" for each Julia module

---

src/gui.jl

Fix fixqtpath

---

src/gui.jl

Add the PySide2 for :qt and :qt_pyside to pygui()

Add PySide2 support to pygui

---

src/conversions.jl
test/runtests.jl

add float(::PyObject)

---

.travis.yml
appveyor.yml

Adds Julia 1.1 to the Travis and AppVeyor tests.

CI on Julia 1.1

---

src/pyinit.jl

add Conda DLL path on Windows

---

deps/depsutils.jl

resize program name/home buffers dynamically

---

.travis.yml
aot/assert_has_pycall.jl
aot/compile.jl
aot/precompile.jl

Fix AOT tests for PackageCompiler 1.x

---

README.md

Easier for users
